const express = require ('express')
const app = express()
const mongoose = require ('mongoose')
const dotenv = require ('dotenv')
const userRoute = require('./routes/user')
const authRoute = require('./routes/auth')
const itemsRoute = require('./routes/items')
const cartRoute = require('./routes/cart')
const orderRoute = require('./routes/order')
dotenv.config()
mongoose.connect(process.env.MONGO_URL)
.then(()=> console.log('Connection Successful')).catch((err)=>{console.log(err)})

app.use(express.json())
app.use('/api/auth', authRoute)
app.use('/api/user', userRoute)
app.use('/api/items', itemsRoute)
app.use('/api/cart', cartRoute)
app.use('/api/order', orderRoute)

app.listen(1000, ()=>{
    console.log('backend server is up')
})